# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cart_pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(255, 326)
        Form.setMinimumSize(QtCore.QSize(255, 326))
        Form.setMaximumSize(QtCore.QSize(255, 326))
        Form.setStyleSheet("background-color:white")
        self.name_display = QtWidgets.QLabel(Form)
        self.name_display.setGeometry(QtCore.QRect(30, 130, 191, 21))
        self.name_display.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.name_display.setObjectName("name_display")
        self.back_profile_1 = QtWidgets.QPushButton(Form)
        self.back_profile_1.setGeometry(QtCore.QRect(140, 260, 101, 21))
        self.back_profile_1.setStyleSheet("background-color:rgb(240,240,240)")
        self.back_profile_1.setObjectName("back_profile_1")
        self.botany_logo = QtWidgets.QLabel(Form)
        self.botany_logo.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.botany_logo.setStyleSheet("")
        self.botany_logo.setText("")
        self.botany_logo.setScaledContents(True)
        self.botany_logo.setObjectName("botany_logo")
        self.accountbalance_display = QtWidgets.QLabel(Form)
        self.accountbalance_display.setGeometry(QtCore.QRect(30, 220, 191, 21))
        self.accountbalance_display.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.accountbalance_display.setObjectName("accountbalance_display")
        self.successfully_paid = QtWidgets.QLabel(Form)
        self.successfully_paid.setGeometry(QtCore.QRect(50, 70, 181, 41))
        self.successfully_paid.setStyleSheet("font: 16pt \"Nirmala UI\";;\n"
"color:rgb(0, 0, 255)")
        self.successfully_paid.setObjectName("successfully_paid")
        self.go_shop = QtWidgets.QPushButton(Form)
        self.go_shop.setGeometry(QtCore.QRect(30, 260, 101, 21))
        self.go_shop.setStyleSheet("background-color:rgb(240,240,240)")
        self.go_shop.setObjectName("go_shop")
        self.studentid_display = QtWidgets.QLabel(Form)
        self.studentid_display.setGeometry(QtCore.QRect(30, 160, 191, 21))
        self.studentid_display.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.studentid_display.setObjectName("studentid_display")
        self.totalprice_display = QtWidgets.QLabel(Form)
        self.totalprice_display.setGeometry(QtCore.QRect(30, 190, 191, 21))
        self.totalprice_display.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.totalprice_display.setObjectName("totalprice_display")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_display.setText(_translate("Form", "Name："))
        self.back_profile_1.setText(_translate("Form", "Back to profile"))
        self.accountbalance_display.setText(_translate("Form", "Account balance："))
        self.successfully_paid.setText(_translate("Form", "Successfully Paid"))
        self.go_shop.setText(_translate("Form", "Continue shopping"))
        self.studentid_display.setText(_translate("Form", "Student ID："))
        self.totalprice_display.setText(_translate("Form", "Total Price"))
