# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 367)
        Form.setMinimumSize(QtCore.QSize(434, 367))
        Form.setMaximumSize(QtCore.QSize(434, 367))
        Form.setStyleSheet("background-color:white")
        self.botany_logo = QtWidgets.QLabel(Form)
        self.botany_logo.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.botany_logo.setStyleSheet("")
        self.botany_logo.setText("")
        self.botany_logo.setScaledContents(True)
        self.botany_logo.setObjectName("botany_logo")
        self.pay_1 = QtWidgets.QPushButton(Form)
        self.pay_1.setGeometry(QtCore.QRect(150, 330, 51, 21))
        self.pay_1.setStyleSheet("background-color:rgb(240,240,240)")
        self.pay_1.setObjectName("pay_1")
        self.back_1 = QtWidgets.QPushButton(Form)
        self.back_1.setGeometry(QtCore.QRect(250, 330, 51, 21))
        self.back_1.setStyleSheet("background-color:rgb(240,240,240)\n"
"")
        self.back_1.setObjectName("back_1")
        self.cart_list = QtWidgets.QListWidget(Form)
        self.cart_list.setGeometry(QtCore.QRect(50, 70, 341, 241))
        self.cart_list.setObjectName("cart_list")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pay_1.setText(_translate("Form", "Pay"))
        self.back_1.setText(_translate("Form", "Back"))
