# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(217, 120)
        Form.setStyleSheet("background-color:white\n"
"")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 221, 41))
        self.label_2.setStyleSheet("font: 12pt \"Nirmala UI\";;\n"
"color:rgb(0, 0, 255)")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 40, 301, 41))
        self.label.setStyleSheet("font: 10pt \"Nirmala UI\";;\n"
"color:rgb(255, 0, 0)")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 80, 56, 17))
        self.pushButton.setStyleSheet("background-color:rgb(240,240,240)")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Payment Failure"))
        self.label.setText(_translate("Form", "Insufficient account balance"))
        self.pushButton.setText(_translate("Form", "Close"))
