# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(616, 400)
        Form.setMinimumSize(QtCore.QSize(616, 400))
        Form.setMaximumSize(QtCore.QSize(616, 400))
        Form.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        Form.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setGeometry(QtCore.QRect(140, 190, 81, 31))
        self.username_label.setStyleSheet("font: 25 13pt \"Yu Gothic Light\";")
        self.username_label.setObjectName("username_label")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(230, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username.setFont(font)
        self.username.setAutoFillBackground(False)
        self.username.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.username.setInputMethodHints(QtCore.Qt.ImhNone)
        self.username.setText("")
        self.username.setMaxLength(32767)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(230, 230, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setText("")
        self.password.setMaxLength(32767)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(140, 230, 81, 31))
        self.password_label.setStyleSheet("font: 25 13pt \"Yu Gothic Light\";")
        self.password_label.setObjectName("password_label")
        self.login = QtWidgets.QPushButton(Form)
        self.login.setGeometry(QtCore.QRect(140, 290, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color:rgb(85, 0, 0);\n"
"font: 16pt \"Sitka Subheading\";\n"
"color:rgb(255, 255, 255)")
        self.login.setObjectName("login")
        self.create_account = QtWidgets.QPushButton(Form)
        self.create_account.setGeometry(QtCore.QRect(260, 330, 111, 21))
        self.create_account.setStyleSheet("background-color:rgb(238, 255, 255);\n"
"font: 10pt \"Palatino Linotype\";\n"
"")
        self.create_account.setObjectName("create_account")
        self.change_password = QtWidgets.QPushButton(Form)
        self.change_password.setGeometry(QtCore.QRect(140, 330, 111, 21))
        self.change_password.setStyleSheet("background-color:rgb(238, 255, 255);\n"
"font: 10pt \"Palatino Linotype\";\n"
"boder:3px")
        self.change_password.setObjectName("change_password")
        self.botany_logo = QtWidgets.QLabel(Form)
        self.botany_logo.setGeometry(QtCore.QRect(260, 20, 151, 141))
        self.botany_logo.setStyleSheet("")
        self.botany_logo.setText("")
        self.botany_logo.setScaledContents(True)
        self.botany_logo.setObjectName("botany_logo")
        self.error_tips = QtWidgets.QLabel(Form)
        self.error_tips.setGeometry(QtCore.QRect(230, 270, 251, 16))
        self.error_tips.setStyleSheet("color:red")
        self.error_tips.setText("")
        self.error_tips.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.error_tips.setObjectName("error_tips")
        self.forget_password = QtWidgets.QPushButton(Form)
        self.forget_password.setGeometry(QtCore.QRect(380, 330, 101, 21))
        self.forget_password.setStyleSheet("background-color:rgb(238, 255, 255);\n"
"font: 10pt \"Palatino Linotype\";")
        self.forget_password.setObjectName("forget_password")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(240, 150, 181, 21))
        self.name.setStyleSheet("font: 14pt \"Yu Gothic\";")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username_label.setText(_translate("Form", "Username"))
        self.password_label.setText(_translate("Form", "Password"))
        self.login.setText(_translate("Form", " Log in"))
        self.create_account.setText(_translate("Form", "Create account"))
        self.change_password.setText(_translate("Form", "Change password"))
        self.forget_password.setText(_translate("Form", "Forget Password"))
        self.name.setText(_translate("Form", "BDSC uniform shop"))
