# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 216)
        Form.setMinimumSize(QtCore.QSize(298, 216))
        Form.setMaximumSize(QtCore.QSize(298, 16777215))
        Form.setStyleSheet("background-color:white")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(50, 60, 61, 21))
        self.name_label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.name_label.setObjectName("name_label")
        self.studentid_label = QtWidgets.QLabel(Form)
        self.studentid_label.setGeometry(QtCore.QRect(50, 90, 91, 21))
        self.studentid_label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.studentid_label.setObjectName("studentid_label")
        self.display_studentid = QtWidgets.QLabel(Form)
        self.display_studentid.setGeometry(QtCore.QRect(140, 90, 101, 21))
        self.display_studentid.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(85, 85, 85)")
        self.display_studentid.setObjectName("display_studentid")
        self.logout = QtWidgets.QPushButton(Form)
        self.logout.setGeometry(QtCore.QRect(190, 20, 61, 21))
        self.logout.setStyleSheet("background-color:rgb(240,240,240);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.logout.setObjectName("logout")
        self.shop_1 = QtWidgets.QPushButton(Form)
        self.shop_1.setGeometry(QtCore.QRect(120, 160, 61, 21))
        self.shop_1.setStyleSheet("background-color:rgb(240,240,240);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.shop_1.setObjectName("shop_1")
        self.cart_1 = QtWidgets.QPushButton(Form)
        self.cart_1.setGeometry(QtCore.QRect(50, 160, 61, 21))
        self.cart_1.setStyleSheet("background-color:rgb(240,240,240);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.cart_1.setObjectName("cart_1")
        self.botany_logo = QtWidgets.QLabel(Form)
        self.botany_logo.setGeometry(QtCore.QRect(20, 10, 91, 41))
        self.botany_logo.setStyleSheet("")
        self.botany_logo.setText("")
        self.botany_logo.setScaledContents(True)
        self.botany_logo.setObjectName("botany_logo")
        self.display_name = QtWidgets.QLabel(Form)
        self.display_name.setGeometry(QtCore.QRect(110, 60, 121, 21))
        self.display_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(85, 85, 85)")
        self.display_name.setObjectName("display_name")
        self.display_accountbalance = QtWidgets.QLabel(Form)
        self.display_accountbalance.setGeometry(QtCore.QRect(180, 120, 101, 21))
        self.display_accountbalance.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(85, 85, 85)")
        self.display_accountbalance.setObjectName("display_accountbalance")
        self.accountbalance_label = QtWidgets.QLabel(Form)
        self.accountbalance_label.setGeometry(QtCore.QRect(50, 120, 131, 21))
        self.accountbalance_label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.accountbalance_label.setObjectName("accountbalance_label")
        self.history = QtWidgets.QPushButton(Form)
        self.history.setGeometry(QtCore.QRect(190, 160, 61, 21))
        self.history.setStyleSheet("background-color:rgb(240,240,240);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.history.setObjectName("history")
        self.name_label.raise_()
        self.studentid_label.raise_()
        self.logout.raise_()
        self.shop_1.raise_()
        self.cart_1.raise_()
        self.botany_logo.raise_()
        self.display_studentid.raise_()
        self.display_name.raise_()
        self.display_accountbalance.raise_()
        self.accountbalance_label.raise_()
        self.history.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "Name："))
        self.studentid_label.setText(_translate("Form", "Student ID："))
        self.display_studentid.setText(_translate("Form", "12345"))
        self.logout.setText(_translate("Form", "Log out"))
        self.shop_1.setText(_translate("Form", "Shop"))
        self.cart_1.setText(_translate("Form", "Cart"))
        self.display_name.setText(_translate("Form", "Leoxie"))
        self.display_accountbalance.setText(_translate("Form", "12345"))
        self.accountbalance_label.setText(_translate("Form", "Account balance："))
        self.history.setText(_translate("Form", "History"))
