# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 389)
        Form.setMinimumSize(QtCore.QSize(271, 389))
        Form.setMaximumSize(QtCore.QSize(271, 389))
        Form.setStyleSheet("background-color:white;")
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(40, 70, 191, 161))
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.product_name = QtWidgets.QLabel(Form)
        self.product_name.setGeometry(QtCore.QRect(40, 240, 191, 21))
        self.product_name.setText("")
        self.product_name.setObjectName("product_name")
        self.size_comboBox = QtWidgets.QComboBox(Form)
        self.size_comboBox.setGeometry(QtCore.QRect(80, 300, 41, 21))
        self.size_comboBox.setObjectName("size_comboBox")
        self.next_1 = QtWidgets.QPushButton(Form)
        self.next_1.setGeometry(QtCore.QRect(100, 330, 51, 21))
        self.next_1.setStyleSheet("background-color:rgb(240,240,240)\n"
"")
        self.next_1.setObjectName("next_1")
        self.size_label = QtWidgets.QLabel(Form)
        self.size_label.setGeometry(QtCore.QRect(40, 300, 41, 21))
        self.size_label.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.size_label.setObjectName("size_label")
        self.price = QtWidgets.QLabel(Form)
        self.price.setGeometry(QtCore.QRect(130, 300, 121, 21))
        self.price.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.price.setText("")
        self.price.setObjectName("price")
        self.quantity_spinBox = QtWidgets.QSpinBox(Form)
        self.quantity_spinBox.setGeometry(QtCore.QRect(40, 330, 51, 22))
        self.quantity_spinBox.setObjectName("quantity_spinBox")
        self.description = QtWidgets.QLabel(Form)
        self.description.setGeometry(QtCore.QRect(40, 270, 191, 21))
        self.description.setText("")
        self.description.setObjectName("description")
        self.back_1 = QtWidgets.QPushButton(Form)
        self.back_1.setGeometry(QtCore.QRect(160, 330, 51, 21))
        self.back_1.setStyleSheet("background-color:rgb(240,240,240)\n"
"")
        self.back_1.setObjectName("back_1")
        self.botany_logo = QtWidgets.QLabel(Form)
        self.botany_logo.setGeometry(QtCore.QRect(10, 10, 121, 51))
        self.botany_logo.setText("")
        self.botany_logo.setScaledContents(True)
        self.botany_logo.setObjectName("botany_logo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_1.setText(_translate("Form", "Next"))
        self.size_label.setText(_translate("Form", "Size:"))
        self.back_1.setText(_translate("Form", "Back"))
