# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(499, 510)
        Form.setMinimumSize(QtCore.QSize(499, 510))
        Form.setMaximumSize(QtCore.QSize(499, 510))
        Form.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.student_id = QtWidgets.QLineEdit(Form)
        self.student_id.setGeometry(QtCore.QRect(40, 270, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.student_id.setFont(font)
        self.student_id.setAutoFillBackground(False)
        self.student_id.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        # This code below only allows the user to type integers instead of strings.
        self.intInputValidation=QtGui.QIntValidator()
        self.student_id.setValidator(self.intInputValidation)
        self.student_id.setInputMethodHints(QtCore.Qt.ImhNone)
        self.student_id.setText("")
        self.student_id.setMaxLength(32767)
        self.student_id.setObjectName("student_id")
        self.create_account = QtWidgets.QLabel(Form)
        self.create_account.setGeometry(QtCore.QRect(40, 40, 291, 31))
        self.create_account.setStyleSheet("font: 20pt \"Nirmala UI Semilight\";\n"
"font: 75 20pt \"Nirmala UI\";\n"
"font-weight:100px")
        self.create_account.setObjectName("create_account")
        self.studentid_label = QtWidgets.QLabel(Form)
        self.studentid_label.setGeometry(QtCore.QRect(40, 250, 91, 16))
        self.studentid_label.setObjectName("studentid_label")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(40, 350, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password.setFont(font)
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setText("")
        self.password.setMaxLength(32767)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(40, 330, 81, 16))
        self.password_label.setObjectName("password_label")
        self.cpassword_label = QtWidgets.QLabel(Form)
        self.cpassword_label.setGeometry(QtCore.QRect(250, 330, 101, 16))
        self.cpassword_label.setObjectName("cpassword_label")
        self.confirm_password = QtWidgets.QLineEdit(Form)
        self.confirm_password.setGeometry(QtCore.QRect(250, 350, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.confirm_password.setFont(font)
        self.confirm_password.setAutoFillBackground(False)
        self.confirm_password.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.confirm_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.confirm_password.setText("")
        self.confirm_password.setMaxLength(32767)
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password.setObjectName("confirm_password")
        self.signup_B = QtWidgets.QPushButton(Form)
        self.signup_B.setGeometry(QtCore.QRect(370, 430, 91, 31))
        self.signup_B.setStyleSheet("font: 13pt \"MS Reference Sans Serif\";\n"
"background-color:rgb(240, 240, 240)")
        self.signup_B.setObjectName("signup_B")
        self.first_name = QtWidgets.QLineEdit(Form)
        self.first_name.setGeometry(QtCore.QRect(40, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.first_name.setFont(font)
        self.first_name.setAutoFillBackground(False)
        self.first_name.setStyleSheet("selection-color: yellow; \n"
"border: 1px solid gray; \n"
" font-size: 16px;\n"
"\n"
"")
        self.first_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_name.setText("")
        self.first_name.setMaxLength(32767)
        self.first_name.setObjectName("first_name")
        self.lastname = QtWidgets.QLineEdit(Form)
        self.lastname.setGeometry(QtCore.QRect(250, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lastname.setFont(font)
        self.lastname.setAutoFillBackground(False)
        self.lastname.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.lastname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lastname.setText("")
        self.lastname.setMaxLength(32767)
        self.lastname.setObjectName("lastname")
        self.firstname_label = QtWidgets.QLabel(Form)
        self.firstname_label.setGeometry(QtCore.QRect(40, 170, 81, 16))
        self.firstname_label.setObjectName("firstname_label")
        self.lastname_label = QtWidgets.QLabel(Form)
        self.lastname_label.setGeometry(QtCore.QRect(250, 170, 81, 16))
        self.lastname_label.setObjectName("lastname_label")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(250, 270, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username.setFont(font)
        self.username.setAutoFillBackground(False)
        self.username.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.username.setInputMethodHints(QtCore.Qt.ImhNone)
        self.username.setText("")
        self.username.setMaxLength(32767)
        self.username.setObjectName("username")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setGeometry(QtCore.QRect(250, 250, 81, 16))
        self.username_label.setObjectName("username_label")
        self.password_code = QtWidgets.QLineEdit(Form)
        self.password_code.setGeometry(QtCore.QRect(40, 430, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password_code.setFont(font)
        self.password_code.setAutoFillBackground(False)
        self.password_code.setStyleSheet("border: 1px solid gray; \n"
"selection-background-color: darkgray; \n"
" font-size: 16px;\n"
"")
        self.password_code.setInputMethodHints(QtCore.Qt.ImhNone)
        self.password_code.setText("")
        self.password_code.setMaxLength(32767)
        self.password_code.setObjectName("password_code")
        self.passwordcode_label = QtWidgets.QLabel(Form)
        self.passwordcode_label.setGeometry(QtCore.QRect(40, 410, 111, 16))
        self.passwordcode_label.setObjectName("passwordcode_label")
        self.studentid_tips = QtWidgets.QLabel(Form)
        self.studentid_tips.setGeometry(QtCore.QRect(40, 310, 191, 16))
        self.studentid_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.studentid_tips.setText("")
        self.studentid_tips.setObjectName("studentid_tips")
        self.tips_label = QtWidgets.QLabel(Form)
        self.tips_label.setGeometry(QtCore.QRect(160, 410, 141, 16))
        self.tips_label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.tips_label.setObjectName("tips_label")
        self.usernmae_tips = QtWidgets.QLabel(Form)
        self.usernmae_tips.setGeometry(QtCore.QRect(250, 310, 191, 16))
        self.usernmae_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.usernmae_tips.setText("")
        self.usernmae_tips.setObjectName("usernmae_tips")
        self.firstname_tips = QtWidgets.QLabel(Form)
        self.firstname_tips.setGeometry(QtCore.QRect(40, 230, 191, 16))
        self.firstname_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.firstname_tips.setText("")
        self.firstname_tips.setObjectName("firstname_tips")
        self.lastname_tips = QtWidgets.QLabel(Form)
        self.lastname_tips.setGeometry(QtCore.QRect(250, 230, 191, 16))
        self.lastname_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.lastname_tips.setText("")
        self.lastname_tips.setObjectName("lastname_tips")
        self.password_tips = QtWidgets.QLabel(Form)
        self.password_tips.setGeometry(QtCore.QRect(40, 390, 191, 16))
        self.password_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.password_tips.setText("")
        self.password_tips.setObjectName("password_tips")
        self.cpassword_tips = QtWidgets.QLabel(Form)
        self.cpassword_tips.setGeometry(QtCore.QRect(250, 390, 191, 16))
        self.cpassword_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.cpassword_tips.setText("")
        self.cpassword_tips.setObjectName("cpassword_tips")
        self.passwordcode_tips = QtWidgets.QLabel(Form)
        self.passwordcode_tips.setGeometry(QtCore.QRect(40, 470, 191, 16))
        self.passwordcode_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.passwordcode_tips.setText("")
        self.passwordcode_tips.setObjectName("passwordcode_tips")
        self.return_B = QtWidgets.QPushButton(Form)
        self.return_B.setGeometry(QtCore.QRect(260, 430, 91, 31))
        self.return_B.setStyleSheet("font: 13pt \"MS Reference Sans Serif\";\n"
"background-color:rgb(240, 240, 240)")
        self.return_B.setObjectName("return_B")
        self.age_label = QtWidgets.QLabel(Form)
        self.age_label.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.age_label.setObjectName("age_label")
        self.age = QtWidgets.QLineEdit(Form)
        self.age.setGeometry(QtCore.QRect(40, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.age.setFont(font)
        self.age.setAutoFillBackground(False)
        self.age.setStyleSheet("selection-color: yellow; \n"
"border: 1px solid gray; \n"
" font-size: 16px;\n"
"\n"
"")
        self.age.setInputMethodHints(QtCore.Qt.ImhNone)
        self.age.setText("")
        self.age.setMaxLength(32767)
        self.age.setObjectName("age")
        # This code below only allows the user to type integers instead of strings.
        self.intInputValidation=QtGui.QIntValidator()
        self.age.setValidator(self.intInputValidation)
        self.age_tips = QtWidgets.QLabel(Form)
        self.age_tips.setGeometry(QtCore.QRect(100, 130, 311, 16))
        self.age_tips.setStyleSheet("color:rgb(255, 0, 0)")
        self.age_tips.setText("")
        self.age_tips.setObjectName("age_tips")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_account.setText(_translate("Form", "Create Your Account"))
        self.studentid_label.setText(_translate("Form", "Student ID"))
        self.password_label.setText(_translate("Form", "Password"))
        self.cpassword_label.setText(_translate("Form", "Confirm Password"))
        self.signup_B.setText(_translate("Form", "Sign up"))
        self.firstname_label.setText(_translate("Form", "First name"))
        self.lastname_label.setText(_translate("Form", "Last name"))
        self.username_label.setText(_translate("Form", "Username"))
        self.passwordcode_label.setText(_translate("Form", "Password code:4 digit"))
        self.tips_label.setText(_translate("Form", "Only for finding back your Password"))
        self.return_B.setText(_translate("Form", "Return"))
        self.age_label.setText(_translate("Form", "Age"))
